### ISSUE TITLE
dicom writer crashes on CentOS for RGB values

### ISSUE THREAD

**Issue by denisri** [brainvisa/soma-io#4]
---

Author Name: **Riviere, Denis** (@denisri)
Original Redmine Issue: 17436, https://bioproj.extra.cea.fr/redmine/issues/17436
Original Date: 2017-10-11

---

Pyaims IO new tests cause a segfault on CentOS, while testing writing a Volume of RGB in DICOM format.

Test command:

```python -m soma.aims.tests.test_pyaims_io -v
```

Possibly another Dcmtk version (3.5.4) issue ?
The top of gdb stacktrace says:

```
#0  0x00002aaaf0d1526b in DcmFileFormat::checkValue(DcmMetaInfo*, DcmDataset*, DcmTagKey const&, DcmObject*, E_TransferSyntax) ()
   from /i2bm/brainvisa/CentOS-5.11-x86_64/dcmtk/lib64/libdcmdata.so
#1  0x00002aaaf0d15fcb in DcmFileFormat::validateMetaInfo(E_TransferSyntax) () from /i2bm/brainvisa/CentOS-5.11-x86_64/dcmtk/lib64/libdcmdata.so
#2  0x00002aaaf0d146e1 in DcmFileFormat::write(DcmOutputStream&, E_TransferSyntax, E_EncodingType, E_GrpLenEncoding, E_PaddingEncoding, unsigned int, unsigned int, unsigned int)
    () from /i2bm/brainvisa/CentOS-5.11-x86_64/dcmtk/lib64/libdcmdata.so
#3  0x00002aaaf0d13ee0 in DcmFileFormat::saveFile(char const*, E_TransferSyntax, E_EncodingType, E_GrpLenEncoding, E_PaddingEncoding, unsigned int, unsigned int, bool) ()
   from /i2bm/brainvisa/CentOS-5.11-x86_64/dcmtk/lib64/libdcmdata.so
#4  0x00002aaaf05daa44 in dcm::SCImageStorageWriter::writeDatasets(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, dcm::DicomProxy&) () from /neurospin/brainvisa/build/CentOS-5.11-x86_64/bug_fix/lib/libsomadicom.so.4.6.0
#5  0x00002aaaf05b5791 in dcm::DicomWriter::write(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, dcm::DicomProxy&) ()
   from /neurospin/brainvisa/build/CentOS-5.11-x86_64/bug_fix/lib/libsomadicom.so.4.6.0
#6  0x00002aaaf05b69c2 in dcm::DicomWriterFactory::write(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, dcm::DicomProxy&, bool) ()
   from /neurospin/brainvisa/build/CentOS-5.11-x86_64/bug_fix/lib/libsomadicom.so.4.6.0
#7  0x00002aaaf05abe2d in dcm::DicomIO::write(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, dcm::DicomProxy&, bool) ()
   from /neurospin/brainvisa/build/CentOS-5.11-x86_64/bug_fix/lib/libsomadicom.so.4.6.0
#8  0x00002aaaf05e9101 in carto::DicomImageWriter<carto::VoxelRGB>::write(carto::VoxelRGB const*, carto::DataSourceInfo&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<long, std::allocator<long> > const&, carto::Object) ()
   from /neurospin/brainvisa/build/CentOS-5.11-x86_64/bug_fix/lib/libsomadicom.so.4.6.0
#9  0x00002aaab4666543 in carto::VolumeFormatWriter<carto::VoxelRGB>::write(carto::Volume<carto::VoxelRGB> const&, carto::rc_ptr<carto::DataSourceInfo>, carto::Object) ()
   from /neurospin/brainvisa/build/CentOS-5.11-x86_64/bug_fix/lib/libcartodata.so.4.6.0
#10 0x00002aaab4607a3b in carto::Writer<carto::Volume<carto::VoxelRGB> >::write(carto::Volume<carto::VoxelRGB> const&, carto::Object, int, int) ()
   from /neurospin/brainvisa/build/CentOS-5.11-x86_64/bug_fix/lib/libcartodata.so.4.6.0
#11 0x00002aaab2a609f5 in aims::Writer<carto::Volume<carto::VoxelRGB> >::write(carto::Volume<carto::VoxelRGB> const&, bool, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const*) () from /neurospin/brainvisa/build/CentOS-5.11-x86_64/bug_fix/lib/libaimsdata.so.4.6.0

```

**Comment by denisri** [comment]
---

Original Redmine Comment
Author Name: **Riviere, Denis** (@denisri)
Original Date: 2017-10-11T08:44:25Z

---

(also happens on Mandriva 2008, also featuring Dcmtk 3.5.4)

**Comment by ylep** [comment]
Is this issue still relevant @denisri, or should we close it?

**Comment by denisri** [comment]
let's say no.
